name: CI/CD Pipeline to Deploy BinaExperts OpenWebUI custom version

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CLASSIC_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/binaexperts/open-webui:latest .

      - name: Push Docker Image
        run: |
          IMAGE_FULL_NAME=ghcr.io/binaexperts/open-webui:latest
          docker push ${IMAGE_FULL_NAME}

      - name: Clean up Docker
        run: |
          docker image prune -f

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # SSH into the server, check Docker Compose, and deploy
      - name: Deploy to Server Using SSH
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/open-webui

            # Check if Docker Compose is available
            if docker compose version &> /dev/null
            then
                echo "Docker Compose is available. Proceeding with deployment..."
                docker compose pull
                docker compose up -d
            else
                echo "Docker Compose not found. Please install Docker Compose on the server."
                exit 1
            fi
          EOF
